openapi: 3.0.0
servers:
  - description: None
    url: none
info:
  description: API Docs for that meal web app
  version: "0.0.1"
  title: that.meal API
  contact:
    email: itanu.romero@aluno.ifsp.edu.br
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: user
    description: All user related endpoints
  - name: recipe
    description: All recipe related endpoints
  - name: rating
    description: All rating related endpoints
  - name: comment
    description: All comment related endpoints
  - name: favourites
    description: All favourites related endpoints
  - name: tags
    description: All tags related endpoints
paths:
  /user:
    get:
      summary: Busca todos os usuários registrados
      tags:
        - user
      description: |
        Listagem de todos os usuários registrados na plataforma caso o usuário for administrador, caso não, apenas mostra seu usuário
      responses:
        '200':
          description: Retorno de usuário
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: bad input parameter
    post:
      summary: Adiciona um novo usuário ao sistema / Registra usuário
      tags:
        - user
      description: Registra usuário
      responses:
        '201':
          description: Novo usuário cadastrado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: Usuário já existe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Dado de inventario a ser adicionado
  /user/{user_id}:
    delete:
      summary: Remove o usuário do ID informado
      tags:
        - user
      description: |
        Deleta o usuário
      parameters: 
        - in: path
          name: user_id
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuário desativado
          content:
            application/text:
              example: Usuário desativado
        '401':
          description: Não permitido
        '404':
          description: Não encontrado
    post:
      summary: Atualiza o usuário do ID informado
      tags:
        - user
      description: |
        Atualiza o usuário
      parameters: 
        - in: path
          name: user_id
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '202':
          description: Usuário Atualizado
          content:
            application/text:
              example: Usuário Atualizado
        '401':
          description: Não permitido
        '404':
          description: Não encontrado

components:
  schemas:
    User:
      type: object
      required:
        - email
        - username
        - birth
        - phone
        - password
        - createdAt
        - updatedAt
        - isAdmin
        - isActive
      properties:
        email:
          type: string
          example: example@example.com
        username:
          type: string
          example: MyUsername
        birth:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        phone:
          type: string
          example: '(11)99999-9999'
        password:
          type: string
          example: string hash
        createdAt:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        updatedAt:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        isAdmin:
          type: boolean
          example: true
        isActive:
          type: boolean
          example: true
    Recipe:
      type: object
      required:
        - name
        - image
        - body
        - createdBy
        - createdAt
        - updatedAt
      properties:
        name:
          type: string
          example: Suco de maçã
        image:
          type: string
          format: url
          example: 'path/to/image'
        body:
          type: string
          example: 'Texto com modo de preparo'
        createdBy:
          $ref: '#/components/schemas/User'
    Recipe-Tags:
      properties:
        recipe:
          $ref: '#/components/schemas/Recipe'
        tag:
           $ref: '#/components/schemas/Tag'
    Rating:
      properties:
        rating: 
          type: integer
          example: 5
        createdBy:
          $ref: '#/components/schemas/User'
        recipe:
          $ref: '#/components/schemas/Recipe'
    Comment:
      properties:
        text: 
          type: string
          example: Muito boa a receita!!!
        createdBy:
          $ref: '#/components/schemas/User'
        recipe:
          $ref: '#/components/schemas/Recipe'
    Favourites:
      properties:
        user:
          $ref: '#/components/schemas/User'
        recipe:
           $ref: '#/components/schemas/Recipe'
    Tag:
      properties:
        name:
          type: string
          example: Suco